Repository Shinhan-MohaeMoyong/MohaeMoyong_Client, pull requests merged in 2025-08, with the labels that each got.

#23 feature : 계좌거래내역 조회 API 연동
  screens/AccountDetailScreen.tsx
  services/api.ts
  types/dto/AccountDetailDTO.ts
  types/dto/index.ts
Labels: feature, 현우

#36 [Client] Refactor : client refactor 모아영 코드 재리팩토링
  hooks/useSavingModel.ts
  screens/AccountDetailScreen.tsx
  screens/AccountScreen.tsx
  screens/AddAccountScreen.tsx
  screens/MohaeyoungScreen.tsx
  screens/SavingScreen.tsx
  services/api.ts
Labels: refactor, 현우

#40 [Client] : Feature/client feature 모아영 계좌생성 api 연결
  screens/AccountScreen.tsx
  screens/AddAccountScreen.tsx
Labels: feature, 현우

#42 feaure : 저축 달성 현황 및 그래프
  components/SavingInfo.tsx
  screens/AccountDetailScreen.tsx
  screens/SavingScreen.tsx
Labels: feature, 성현

#55 refactor : 계좌 상세보기 요청dto
  screens/AccountDetailScreen.tsx
Labels: refactor, 성현
